import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import PageLayout from '../components/layout/PageLayout';
import './Auth.css';

export default function TwoFAPage() {
  const navigate = useNavigate();
  const [code, setCode] = useState(['', '', '', '', '', '']);
  const [loading, setLoading] = useState(false);
  const inputRefs = React.useMemo(() => [
    React.createRef(), React.createRef(), React.createRef(), 
    React.createRef(), React.createRef(), React.createRef()
  ], []);

  // Focus first input on mount
  useEffect(() => {
    inputRefs[0].current?.focus();
  }, [inputRefs]);

  const handleSubmit = (e) => {
    e.preventDefault();
    
    setLoading(true);
    // Simulate network request
    setTimeout(() => {
      navigate('/portal');
    }, 1200);
  };

  const handleChange = (index, value) => {
    // Only allow numbers
    if (!/^[0-9]*$/.test(value)) return;
    
    const newCode = [...code];
    newCode[index] = value;
    setCode(newCode);

    // Auto-advance
    if (value !== '' && index < 5) {
      inputRefs[index + 1].current.focus();
    }
  };

  const handleKeyDown = (index, e) => {
    if (e.key === 'Backspace' && code[index] === '' && index > 0) {
      inputRefs[index - 1].current.focus();
    }
  };

  const handlePaste = (e) => {
    e.preventDefault();
    const pasteData = e.clipboardData.getData('text/plain').slice(0, 6).split('');
    if (pasteData.every(char => /^[0-9]$/.test(char))) {
      const newCode = [...code];
      pasteData.forEach((char, i) => {
        newCode[i] = char;
      });
      setCode(newCode);
      if (pasteData.length < 6) {
        inputRefs[pasteData.length].current.focus();
      } else {
        inputRefs[5].current.focus();
      }
    }
  };

  return (
    <PageLayout>
      <div className="auth-page">
        <div className="auth-card">
          <p className="text-2xs text-mono uppercase tracking-widest text-signal-violet auth-eyebrow" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <ShieldCheck size={14} /> Security Challenge
          </p>
          <h1 className="auth-heading">Verify Identity.</h1>
          <p className="auth-subhead">Enter the 6-digit verification code generated by your authenticator app.</p>
          
          <form className="auth-form" onSubmit={handleSubmit}>
            <div className="auth-code-container">
              {code.map((digit, index) => (
                <input
                  key={index}
                  ref={inputRefs[index]}
                  type="text"
                  inputMode="numeric"
                  maxLength={1}
                  className="auth-code-input"
                  value={digit}
                  onChange={(e) => handleChange(index, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(index, e)}
                  onPaste={index === 0 ? handlePaste : undefined}
                />
              ))}
            </div>
            
            <button type="submit" className="auth-submit" disabled={loading}>
              {loading ? (
                <div className="spinner"></div>
              ) : (
                <>Verify & Proceed <ArrowRight size={16} /></>
              )}
            </button>
            
            <div className="auth-resend">
              <span>Lost access to your device? </span>
              <button type="button" className="auth-resend-btn">Use backup code</button>
            </div>
          </form>
        </div>
      </div>
    </PageLayout>
  );
}
